---

- name: Install filebeat package
  yum:
    name: filebeat
    state: present

- name: Create filebeat config directory
  file:
    path: /etc/filebeat/configs
    mode: 0755
    owner: root
    group: root
    state: directory

- name: Configure filebeat
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify: Restart filebeat

- name: Add filebeat configs
  template:
    src: "{{ item.src }}"
    dest: "/etc/filebeat/configs/{{ item.dest }}"
  notify: Restart filebeat
  when: filebeat_configs is defined
  with_items: "{{ filebeat_configs }}"

- name: Enable and start filebeat
  service:
    name: filebeat
    state: "{{ 'started' if 'filebeat' in enabled_services else 'stopped' }}"
    enabled: "{{ 'True' if 'filebeat' in enabled_services else 'False' }}"
