---
scenario:
  name: single-node  # optional
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: true
vmware:
  network_name: ${VMWARE_NETWORK}
  datastore: ${VMWARE_DATASTORE}
  datacenter: ${VMWARE_DATACENTER}
  vcenter_address: ${VCENTER_ADDRESS}
  esxi_hostname: ${VCENTER_ESXI}
  validate_certs: true
  resource_pool: "Resources"
lint:
  name: yamllint
platforms:
  - name: "rock-molecule-${MOLECULE_SCENARIO_NAME}${TOX_ENVNAME}-instance-1"
    memory: 16384
    cpu: 4
    disk_size: 64
    guest_id: ${TEMPLATE_DISTRO-centos}7_64Guest
    template_pattern: '^template-${TEMPLATE_DISTRO-centos}-7'
    children:
      - rock
      - web
      - es_masters
      - es_data
      - es_ingest
      - zookeeper
    groups:
      - lighttpd
      - sensors
      - bro
      - fsf
      - kafka
      - stenographer
      - suricata
      - filebeat
      - elasticsearch
      - docket
      - kibana
      - logstash
provisioner:
  name: ansible
  log: true
  become: true
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/roles"
    VMWARE_USER: "${VMWARE_USERNAME}"
    VMWARE_PASSWORD: "${VMWARE_PASSWORD}"
    RHSM_ORGID: "${RHSM_ORGID}"
    RHSM_ACTIVATION_KEY: "${RHSM_ACTIVATION_KEY}"
  options:
    extra-vars:
      rock_conf_dir: "${MOLECULE_EPHEMERAL_DIRECTORY}/etc"
      rock_config: "${MOLECULE_EPHEMERAL_DIRECTORY}/etc/config"
      rock_monifs: ["dummy0"]
      rock_disable_offline_repo: true
      rock_enable_testing: true
      # Must static the es_mem var for now until #386 is resolved
      es_mem: 8
  config_options:
    defaults:
      callback_whitelist: timer,profile_tasks,profile_role
    connection:
      pipelining: true
  inventory:
    group_vars:
      elasticsearch:
        node_master: false
        node_data: false
        node_ingest: false
      es_masters:
        node_master: true
      es_data:
        node_data: true
      es_ingest:
        node_ingest: true
  lint:
    name: ansible-lint
    config_options:
      defaults:
        roles_path: "${MOLECULE_PROJECT_DIRECTORY}/roles"

verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: false
