---
scenario:
  name: multi-node  # optional
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: true
vmware:
  network_name: CyberLab
  datastore: vmstore
  datacenter: Datacenter
  vcenter_address: vcenter.rocklab.lan
  esxi_hostname: 192.168.73.40
  validate_certs: false
  resource_pool: "Resources"
lint:
  name: yamllint
platforms:
  - name: "rock-molecule-${MOLECULE_SCENARIO_NAME}-instance-1"
    memory: 16384
    cpu: 4
    disk_size: 64
    guest_id: centos7_64Guest
    template_pattern: '^template-centos-7'
    groups:
      - rock
      - zookeeper
      - sensors
      - bro
      - fsf
      - kafka
      - stenographer
      - suricata
      - suricata_update
      - filebeat
      - logstash
  - name: "rock-molecule-${MOLECULE_SCENARIO_NAME}-instance-2"
    memory: 16384
    cpu: 4
    disk_size: 64
    guest_id: centos7_64Guest
    template_pattern: '^template-centos-7'
    groups:
      - es_masters
      - es_data
      - es_ingest
      - web
      - lighttpd
      - elasticsearch
      - docket
      - kibana
  - name: "rock-molecule-${MOLECULE_SCENARIO_NAME}-instance-3"
    memory: 16384
    cpu: 4
    disk_size: 64
    guest_id: centos7_64Guest
    template_pattern: '^template-centos-7'
    groups:
      - es_masters
      - es_data
      - es_ingest
      - elasticsearch
  - name: "rock-molecule-${MOLECULE_SCENARIO_NAME}-instance-4"
    memory: 16384
    cpu: 4
    disk_size: 64
    guest_id: centos7_64Guest
    template_pattern: '^template-centos-7'
    groups:
      - es_masters
      - es_data
      - es_ingest
      - elasticsearch
provisioner:
  name: ansible
  log: true
  become: true
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/roles"
    VMWARE_USER: "${VMWARE_USER}"
    VMWARE_PASSWORD: "${VMWARE_PASSWORD}"
  options:
    extra-vars:
      rock_conf_dir: "${MOLECULE_EPHEMERAL_DIRECTORY}/etc"
      rock_config: "${MOLECULE_EPHEMERAL_DIRECTORY}/etc/config"
      rock_monifs: ["dummy0"]
      rock_disable_offline_repo: true
      rock_enable_testing: true
      elastic_baseurl: http://internal-mirror.cyberlab.lan/elastic/6.x/
      # Must static the es_mem var for now until #386 is resolved
      es_mem: 8
  config_options:
    defaults:
      callback_whitelist: timer,profile_tasks,profile_role
    connection:
      pipelining: true
  inventory:
    group_vars:
      elasticsearch:
        node_master: true
        node_data: true
        node_ingest: true
      es_masters:
        node_master: true
      es_data:
        node_data: true
      es_ingest:
        node_ingest: true
    hosts:
      all:
        children:
          rock:
          web:
          lighttpd:
            children:
              web:
          sensors:
            children:
              rock:
          bro:
            children:
              sensors:
          fsf:
            children:
              sensors:
          kafka:
            children:
              sensors:
          stenographer:
            children:
              sensors:
          suricata:
            children:
              sensors:
          suricata_update:
            children:
              suricata:
          filebeat:
            children:
              fsf:
              suricata:
          zookeeper:
          elasticsearch:
            children:
              es_masters:
              es_data:
              es_ingest:
          es_masters:
          es_data:
          es_ingest:
          docket:
            children:
              web:
          kibana:
            children:
              web:
          logstash:
            children:
              sensors:
  lint:
    name: ansible-lint
    config_options:
      defaults:
        roles_path: "${MOLECULE_PROJECT_DIRECTORY}/roles"

verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: false
