######################################################
################# Setup Kibana #######################
######################################################
---

# This is here because Kubernetes repeatedly failed to download the image.
# See: https://github.com/kubernetes/kubernetes/issues/59376
# Pulling it through Docker resolves the issue
- name: Perform image download workaround
  docker_image:
    name: "{{ suricata_image }}:{{ suricata_ver }}"

- name: Create config directory
  file:
    path: "{{ suricata_dir }}"
    state: directory
    owner: root
    group: root
    mode: u+rw,g+rw

- name: Copy files
  copy:
    src: "files/{{ item }}"
    dest: "{{ suricata_dir }}/{{ item }}"
    group: root
    owner: root
    mode: 0644
  with_items:
    - suricata.yaml.tmpl
    - filebeat.yml.tmpl
    - suricata.yaml.conf
    - filebeat.yml.conf

- name: Install templates
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ suricata_dir }}/{{ item }}"
    group: root
    owner: root
    mode: 0644
  with_items:
    - deploy.yml

- name: Create ConfigMap
  shell: |
    kubectl delete configmap suricata
    kubectl create configmap suricata --from-file={{ suricata_dir }}/suricata.yaml.tmpl \
      --from-file={{ suricata_dir }}/filebeat.yml.tmpl \
      --from-file={{ suricata_dir }}/suricata.yaml.conf \
      --from-file={{ suricata_dir }}/filebeat.yml.conf

- name: Deploy
  shell: |
    kubectl delete -f {{ suricata_dir }}/deploy.yml
    kubectl apply -f {{ suricata_dir }}/deploy.yml
    while [ $(kubectl get -f {{ suricata_dir }}/deploy.yml | tail -n +2 | awk '{print $5}') == '0' ]; do
      echo -n .;
      sleep 1;
    done;
