#######################################################
#####################  Firewall  ######################
#######################################################
---
-
  name: Install Firewalld package
  yum:
    name: firewalld
    state: installed
    
- name: Enable and start firewalld
  service:
    name: firewalld
    enabled: yes
    state: started

- name: Configure firewalld
  firewalld:
    port: "{{ item[1].port }}"
    source: "{{ item[0] }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_nested:
    - "{{ rock_mgmt_nets }}"
    -
      - { port: "22/tcp" }