#######################################################
#################### DNS Changes ######################
#######################################################
---
- 
  name: Set hostname in hosts file
  lineinfile:
    dest: /etc/hosts
    insertafter: 127.0.0.1
    line: 127.0.0.2  {{ rock_fqdn }}  {{ rock_hostname }}

- 
  name: Set system hostname
  hostname:
    name: "{{ rock_fqdn }}"