---
# handlers file for rocknsm.docket
- name: Cleanup csr on docket host
  file:
    path: "{{ docket_x509_key }}.csr"
    state: absent
  when: inventory_hostname in groups['docket'] | bool

- name: Cleanup csr on sensor hosts
  file:
    path: "{{ steno_certs_dir }}/{{ hostvars[item].inventory_hostname }}.csr"
    state: absent
  loop: "{{ groups['docket'] }}"
  when: inventory_hostname in groups['stenographer'] | bool

- name: Restart redis
  service:
    name: redis
    state: restarted
  when: docket_enable | bool

- name: Seed random key
  lineinfile:
    path: /etc/docket/prod.yml
    regexp: 'XX_NOT_A_SECRET_XX'
    line: "SECRET_KEY: {{ docket_secret }}"
    state: present

- name: Restart docket celery services
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - docket-celery-io
    - docket-celery-query
  when: docket_enable | bool

- name: Restart docket uwsgi
  service:
    name: docket
    state: restarted
  when: docket_enable | bool

- name: Restart lighttpd
  service:
    name: lighttpd
    state: restarted
  when: docket_enable | bool
