#!/bin/bash
# 90-issue-update
# Description: Updates /etc/issue using template /etc/issue.in and
#              values from system at time of interface up

IF=$1
STATUS=$2

function update_issue() {
  . /etc/os-release
  OS_RELEASE="$( cat /etc/system-release )";
  cat /etc/issue.in | sed "s/{{OS_RELEASE}}/${OS_RELEASE}/" > /etc/issue

  # Reset gettys where a user is not logged in
  GETTYS=$(systemctl list-units | grep "getty@" | grep -vE "$(who | awk '{ print $2 }'|paste -sd'|' )" | awk '{print $1}'|paste -s)
  systemctl restart $(GETTYS)
}

if [ "$IF" <> "lo" ]
then
  case "$2" in
    up)
      logger -s "NM Script up triggered"
      update_issue
      ;;
    down)
      logger -s "NM Script down triggered"
      update_issue
      ;;
    *)
      ;;
  esac
fi
