# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<EOF

# Setup RockNSM Repo
yum install -y https://copr-be.cloud.fedoraproject.org/results/@rocknsm/rocknsm-2.1/epel-7-x86_64/00720349-rock-release/rock-release-2.1-1.noarch.rpm epel-release
sed -i '/enabled=/ s/0/1/' /etc/yum.repos.d/rocknsm-testing.repo

yum install -y ansible python2-pyOpenSSL stenographer

/usr/bin/stenokeys.sh stenographer stenographer

# Run the test
cd /vagrant/rocknsm.docket
./test.sh
EOF

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  # Public Network
  config.vm.define :node do |node|
    node.vm.network :public_network,
      :dev => "virbr0",
      :mode => "bridge",
      :type => "bridge"
  end

  config.vm.synced_folder '../', '/vagrant', type: 'rsync'

  config.vm.provision "shell" do |s|
      s.inline = $script
      s.keep_color = true
  end
end
