# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<EOF
yum install -y ansible pyOpenSSL
cd /vagrant/rocknsm.docket
./test.sh
EOF

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.synced_folder '../', '/vagrant', type: 'rsync'

  config.vm.provision "shell" do |s|
      s.inline = $script
      s.keep_color = true
  end
end
