---
# handlers file for Bro

- name: Configure monitor interfaces
  shell: >
    for intf in {{ rock_monifs | join(' ') }}; do
      /sbin/ifup ${intf};
    done

- name: Reload zeek
  service:
    name: zeek
    state: restarted
  when: local_services | selectattr('name', 'equalto', 'zeek') | map(attribute='enabled') | first | bool
