---
# handlers file for Bro

- name: Configure monitor interfaces
  shell: >
    for intf in {{ rock_monifs | join(' ') }}; do
      /sbin/ifup ${intf};
    done

- name: Reload zeek
  service:
    name: zeek
    state: restarted
  when: "'zeek' in enabled_services"
