#!/bin/bash


function feature_enabled() {
  grep -qiE "^enable_$1: (true|yes)" /etc/rocknsm/config.yml;
  return $?
}

if feature_enabled fsf; then
  echo "Stopping FSF..."
  systemctl stop fsf
fi

if feature_enabled suricata; then
  echo "Stopping Stenographer..."
  systemctl stop stenographer
fi

if feature_enabled suricata; then
  echo "Stopping Suricata..."
  systemctl stop suricata
fi

if feature_enabled snort; then
  echo "Stopping Snort..."
  systemctl stop snortd
fi

if feature_enabled bro; then
  echo "Stopping Bro..."
  systemctl stop broctl
fi

if feature_enabled logstash; then
  echo "Stopping Logstash..."
  systemctl stop logstash
fi

if feature_enabled kibana; then
  echo "Stopping Kibana..."
  systemctl stop kibana
fi

if feature_enabled elasticsearch; then
  echo "Stopping Elasticsearch..."
  systemctl stop elasticsearch
fi

if feature_enabled kafka; then
  echo "Stopping Kafka..."
  systemctl stop kafka
fi

if feature_enabled zookeeper; then
  echo "Stopping Zookeeper..."
  systemctl stop zookeeper
fi

exit 0
