---
- name: Enable and restart lighttpd
  systemd:
    name: lighttpd
    state: >-
      {%- if local_services | selectattr('name', 'equalto', 'lighttpd') | map(attribute='enabled') | first | bool or
      local_services | selectattr('name', 'equalto', 'docket') | map(attribute='enabled') | first | bool -%}
        restarted
      {%- else -%}
        stopped
      {%- endif -%}
    enabled: >-
      {%- if local_services | selectattr('name', 'equalto', 'lighttpd') | map(attribute='enabled') | first | bool or
      local_services | selectattr('name', 'equalto', 'docket') | map(attribute='enabled') | first | bool -%}
        True
      {%- else -%}
        False
      {%- endif -%}
