---
- name: Enable and restart lighttpd
  systemd:
    name: lighttpd
    state: >-
      {%- if rock_services | selectattr('name', 'equalto', 'lighttpd') | map(attribute='enabled') or rock_services | selectattr('name', 'equalto', 'docket') | map(attribute='enabled') -%}
        restarted
      {%- else -%}
        stopped
      {%- endif -%}
    enabled: >-
      {%- if rock_services | selectattr('name', 'equalto', 'lighttpd') | map(attribute='enabled') or rock_services | selectattr('name', 'equalto', 'docket') | map(attribute='enabled') -%}
        True
      {%- else -%}
        False
      {%- endif -%}
