
---
###############################################################################
#      :::====  :::====  :::===== :::  === :::= === :::===  :::=======        #
#      :::  === :::  === :::      ::: ===  :::===== :::     ::: === ===       #
#      =======  ===  === ===      ======   ========  =====  === === ===       #
#      === ===  ===  === ===      === ===  === ====     === ===     ===       #
#      ===  ===  ======   ======= ===  === ===  === ======  ===     ===       #
###############################################################################
# This configuration file can be used to override any of the installation
# variables that affect the deployment of RockNSM. Take care when modifying
# these options. The defaults should be used unless you really know what you
# are doing!



###############################################################################
#                             NEXT STEP: Deployment
###############################################################################
# Any time the settings in this config file are updated, you will need to re-run
# the deployment scripts to pick up the changes by running:
#
#    /usr/local/bin/deploy_rock.sh
#
# For more information refer to the full documentation at: https://rocknsm.io
