== Release Notes

Some of the biggest changes with ROCK 2.0 are upgrading all the software to the latest versions. Here's a list.

[options="header"]
|===
| Software | Version | Notes
| CentOS | 7.3 (1611) | 
| Bro    | 2.5 | Plugins for kafka output and af_packet capture
| Suricata | 3.1.3 | _This is now the default signature-based IDS_
| Snort | 2.9.8.3 | _This is now an optional replacement for suricata_
| Stenographer | Git 12106b | 
| Kafka | 0.10.0.0 |
| Elasticsearch | 5.1.1 |
| Logstash | 5.1.1 | 
| Kibana | 5.1.1 |
| Ansible | 2.2.0.0 | 
|===

On top of software updates, we also changed the deployment mechanism to using Ansible as the primary mechanism. We did this for a few reasons: I used it for one of my full-time projects, it's super lightweight and available in EPEL, doesn't require an agent, super easy to understand. I'm hoping that ultimately this makes the platform more approachable to a wider community and better suitable to offline or isolated install environments, which I've frequently encountered for sensor networks.

On that last note, we now have an ISO that _should_ contain everything you need to deploy. The ISO is merely a snapshot of packages available at the time and latest snapshot of various Git repositories.



