#!/bin/bash

function feature_enabled() {
  if grep -qiE "^with_$1: (true|yes)" /etc/rocknsm/config.yml; then
    grep -qiE "^enable_$1: (true|yes)" /etc/rocknsm/config.yml;
    return $?
  else
    return 1
  fi
}

if feature_enabled zookeeper; then
  echo "Starting Zookeeper..."
  systemctl start zookeeper
  sleep 5
  systemctl status zookeeper | egrep "^\s*Active"
fi

if feature_enabled elasticsearch; then
  echo "Starting Elasticsearch..."
  systemctl start elasticsearch
  sleep 5
  systemctl status elasticsearch | egrep "^\s*Active"
fi

if feature_enabled kafka; then
  echo "Starting Kafka..."
  systemctl start kafka
  sleep 5
  systemctl status kafka | egrep "^\s*Active"
fi

if feature_enabled logstash; then
  echo "Starting Logstash..."
  systemctl start logstash
  sleep 5
  systemctl status logstash | egrep "^\s*Active"
fi

if feature_enabled kibana; then
  echo "Starting Kibana..."
  systemctl start kibana
  sleep 5
  systemctl status kibana | egrep "^\s*Active"
fi

if feature_enabled suricata; then
  echo "Starting Suricata..."
  systemctl start suricata
  sleep 5
  systemctl status suricata | egrep "^\s*Active"
fi

if feature_enabled snort; then
  echo "Starting Snort..."
  systemctl start snortd
  sleep 5
  systemctl status snortd | egrep "^\s*Active"
fi

if feature_enabled bro; then
  echo "Starting Bro..."
  systemctl start bro
  sleep 5
  systemctl status bro | egrep "^\s*Active"
fi

if feature_enabled stenographer; then
  echo "Starting Stenographer..."
  systemctl start stenographer
  sleep 5
  for item in $(ls  /etc/stenographer/config* | awk -F. '/\./ { print $2 }')
  do
    systemctl status stenographer@${item} | egrep "^\s*Active" | cat <( echo -n "   ${item}: ") -
  done
fi

if feature_enabled fsf; then
  echo "Starting FSF..."
  systemctl start fsf
  sleep 5
  systemctl status fsf | egrep "^\s*Active"
fi

exit 0
