---
# handlers file for zookeeper
- name: Restart zookeeper
  systemd:
    name: zookeeper
    state: "{{ 'restarted' if local_services | selectattr('name', 'equalto', 'zookeeper') | map(attribute='enabled') | first | bool else 'stopped' }}"
