#!/bin/bash

action=$1
psprocs=( zookeeper kafka bro suricata filebeat elasticsearch logstash kibana stenographer fsf docket )

function feature_enabled() {
  if grep -qiE "^with_$1: (true|yes)" /etc/rocknsm/config.yml; then
    if grep -qiE "^enable_$1: (true|yes)" /etc/rocknsm/config.yml; then
      return $?
    else
      false
    fi
  else
    false
  fi
}

function reverse()
{
  local arrayname=${1:?Array name required} array revarray e
  eval "array=( \"\${$arrayname[@]}\" )"
  for e in "${array[@]}"
  do
    revarray=( "$e" "${revarray[@]}" )
  done
  eval "$arrayname=( \"\${revarray[@]}\" )"
}

for i in $(ls -1 /etc/stenographer/config.* | awk -F. '{print $2}'); do
  psprocs+=("stenographer@${i}")
done

case $action in
  "stop")
    reverse psprocs
    for proc in "${psprocs[@]}"; do
      echo "${proc^^}: stopping..."
      systemctl stop ${proc}
      # Lets also make sure the service is disabled
      if [[ $(systemctl is-enabled ${proc}) == 'enabled' ]] && ! $(feature_enabled ${proc}); then
        echo "${proc^^} is set to disabled in RockNSM config but is currently enabled in systemctl."
        echo "Disabling ${proc^^} in systemctl..."
        systemctl disable --quiet ${proc}
      fi
    done
    ;;
  "start")
    for proc in "${psprocs[@]}"; do
      if feature_enabled ${proc}; then
        echo "${proc^^}: starting..."
        systemctl start ${proc}
        # Lets also make sure the service is enabled
        if [[ $(systemctl is-enabled ${proc}) == 'disabled' ]]; then
          echo "${proc^^} is set to enabled in RockNSM config but is currently disabled in systemctl."
          echo "Enabling ${proc^^} in systemctl..."
          systemctl enable ${proc}
        fi
      fi
    done
    ;;
  "status")
    for proc in "${psprocs[@]}"; do
      echo "${proc^^}":
      systemctl is-active --quiet ${proc}
      if [[ $? -eq 0 ]]; then
        prefix="[1;32m"
      else
        prefix="[1;31m"
      fi
      echo "${prefix}$(systemctl status ${proc} | grep Active)i[0m"
    done
    ;;
  "reset-failed")
    for proc in "${psprocs[@]}"; do
      echo "${proc^^}: resetting status..."
      systemctl reset-failed ${proc}
    done
    ;;
  *)
    echo "rockctl: Usage: rockctl {start|stop|status|reset-failed}"
esac

exit 0
