---
# tasks file for bro

- name: Install packages
  yum:
    name:
      - bro
      - bro-plugin-af_packet
      - bro-plugin-kafka
      - bro-plugin-gquic
      - bro-plugin-communityid
      - GeoIP
      - GeoIP-update
      - postfix
    state: installed

- name: Set monitor interface config
  template:
    src: templates/ifcfg-monif.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ item }}
    mode: 0644
    owner: root
    group: root
    force: true
  loop: "{{ rock_monifs }}"

- name: Configure local ifup script
  template:
    src: templates/ifup-local.j2
    dest: /sbin/ifup-local
    mode: 0755
    owner: root
    group: root
    force: true
  notify: Configure monitor interfaces

- name: Configure GeoIP Update
  copy:
    src: GeoIP.conf
    dest: /etc/GeoIP.conf

# There's an issue w/ geoipupdate when env is empty
- name: Update GeoIP
  shell: >
    if [ "x$HTTP_PROXY" == "x" ]; then
        unset HTTP_PROXY;
    fi
    if [ "x$http_proxy" == "x" ]; then
        unset http_proxy;
    fi
    if [ "x$HTTPS_PROXY" == "x" ]; then
        unset HTTPS_PROXY;
    fi
    if [ "x$https_proxy" == "x" ]; then
        unset https_proxy;
    fi
    /usr/bin/geoipupdate
  args:
    creates: /usr/share/GeoIP/GeoLiteASNum.dat
  register: result
  failed_when: (result.rc != 0) and (result.rc != 1)

- name: Create GeoIP symlinks
  file:
    src: "/usr/share/GeoIP/{{ item.src }}"
    dest: "/usr/share/GeoIP/{{ item.dest }}"
    force: true
    state: link
  loop:
    - { src: 'GeoLiteCity.dat', dest: 'GeoIPCity.dat' }
    - { src: 'GeoLiteCountry.dat', dest: 'GeoIPCountry.dat' }
    - { src: 'GeoLiteASNum.dat', dest: 'GeoIPASNum.dat' }
    - { src: 'GeoLiteCityv6.dat', dest: 'GeoIPCityv6.dat' }

- name: Create bro group
  group:
    name: "{{ bro_group }}"
    state: present
    system: true

- name: Create bro user
  user:
    name: "{{ bro_user }}"
    comment: "bro service account"
    createhome: false
    group: "{{ bro_group }}"
    home: /var/spool/bro
    shell: /sbin/nologin
    system: true
    state: present

- name: Create bro directories
  file:
    path: "{{ item }}"
    mode: 0755
    owner: "{{ bro_user }}"
    group: "{{ bro_group }}"
    state: directory
    setype: var_log_t
  loop:
    - "{{ bro_data_dir }}"
    - "{{ bro_data_dir }}/logs"
    - "{{ bro_data_dir }}/spool"

- name: Create /opt/bro for wandering users
  file:
    dest: "/opt/bro"
    state: directory

- name: Create note to wandering users
  copy:
    dest: "/opt/bro/README.md"
    content: |
      Hey! Where's my Bro?
      =========================
      RockNSM has aligned the Bro package to be inline with Fedora packaging
      guidelines in an effort to push the package upstream for maintenance.
      Fedora and EPEL have a great community and we believe others can benefit
      from our hard work.
      Here's where you can find your stuff:
      Bro configuration files
      -----------------------
      /opt/bro/etc -> /etc/bro
      Bro site scripts
      -----------------------
      /opt/bro/share/bro/site -> /usr/share/bro/site
      Bro logs and spool dirs (same as previous ROCK iterations)
      -----------------------
      /opt/bro/logs -> /data/bro/logs
      /opt/bro/spool -> /data/bro/spool

- name: Create bro configs
  template:
    src: "{{ item }}.j2"
    dest: "{{ bro_sysconfig_dir }}/{{ item }}"
    mode: 0644
    owner: root
    group: root
  notify: Reload bro
  loop:
    - node.cfg
    - broctl.cfg
    - networks.cfg

- name: Add bro custom scripts directory
  file:
    path: "{{ bro_site_dir }}/scripts"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Set permissions on broctl scripts
  file:
    path: "{{ bro_prefix }}/share/broctl/scripts"
    owner: "{{ bro_user }}"
    group: "{{ bro_user }}"
    mode: 0755
    state: directory

- name: Add README to scripts
  copy:
    src: bro-scripts-readme.txt
    dest: "{{ bro_site_dir }}/scripts/README.txt"
    mode: 0644
    owner: root
    group: root

- name: Checkout ROCK bro scripts
  git:
    repo: "{{ bro_rockscripts_repo }}"
    dest: "{{ bro_site_dir }}/scripts/rock"
    version: "{{ bro_rockscripts_branch }}"
  when: rock_online_install

- name: Deploy offline ROCK bro scripts
  unarchive:
    src: "{{ rock_cache_dir }}/{{ bro_rockscripts_filename }}"
    dest: "{{ bro_site_dir }}/scripts/"
    owner: root
    group: root
    creates: "{{ bro_site_dir }}/scripts/rock-scripts-{{ bro_rockscripts_branch | replace ('/', '-') }}"
    remote_src: true
  when: not rock_online_install | bool

- name: Symlink offline ROCK bro scripts
  file:
    src: "{{ bro_site_dir }}/scripts/rock-scripts-{{ bro_rockscripts_branch | replace ('/', '-') }}"
    dest: "{{ bro_site_dir }}/scripts/rock"
    state: link
    force: true
  when: not rock_online_install | bool

- name: Update owner for ROCK bro scripts
  file:
    path: "{{ bro_site_dir }}/scripts/rock"
    owner: "{{ bro_user }}"
    group: "{{ bro_group }}"
    state: directory
    recurse: true
    follow: true
  tags:
    - bro_scripts

- name: Add ROCK scripts to local.bro
  lineinfile:
    dest: "{{ bro_site_dir }}/local.bro"
    line: "@load scripts/rock # ROCK NSM customizations"
    state: present

- name: Enable bro kafka output to local.bro
  lineinfile:
    dest: "{{ bro_site_dir }}/local.bro"
    line: "@load scripts/rock/plugins/kafka"
    state: present
  when: "rock_services | selectattr('name', 'equalto', 'kafka') | map(attribute='enabled')"

- name: Add bro aliases
  copy:
    src: profile.d-bro.sh
    dest: /etc/profile.d/bro.sh
    mode: 0644
    owner: root
    group: root

- name: Add broctl wrapper for admin use
  copy:
    src: broctl.sh
    dest: /usr/sbin/broctl
    mode: 0754
    owner: root
    group: root

- name: Set bro capabilities
  capabilities:
    path: /usr/bin/bro
    capability: "{{ item }}"
    state: present
  loop:
    - "cap_net_raw+eip"
    - "cap_net_admin+eip"

- name: Set capstats capabilities
  capabilities:
    path: /usr/bin/capstats
    capability: "{{ item }}"
    state: present
  loop:
    - "cap_net_raw+eip"
    - "cap_net_admin+eip"

- name: Set broctl cron
  cron:
    name: "broctl maintenance"
    minute: "*/5"
    cron_file: rocknsm_broctl
    user: "{{ bro_user }}"
    job: "/usr/bin/broctl cron >/dev/null 2>&1"

- name: Initialize bro scripts for workers
  command: /usr/bin/broctl install
  args:
    creates: "{{ bro_data_dir }}/spool/broctl-config.sh"
  become: true
  become_user: "{{ bro_user }}"

- name: Check status of interfaces
  command: >
    /usr/sbin/ip -oneline link show dev {{ item }}
  register: iplink
  changed_when: false
  loop: "{{ rock_monifs }}"

- name: Bring up interfaces
  command: >
    /usr/sbin/ip -oneline link set dev {{ item.stdout.split(':')[1] | trim }} up
  when: item.stdout is search("state DOWN")
  loop: "{{ iplink.results }}"

- name: Discover facts about data mount
  set_fact:
    rock_mounts:
      mount: "{{ item.mount }}"
      device: "{{ item.device }}"
      size_total: "{{ item.size_total }}"
  loop:
    "{{ ansible_mounts }}"
  when: (default_mount is defined and item.mount == default_mount and rock_mounts is not defined)

- name: Determining if quotas are enabled
  shell: grep "{{ default_mount }}" /etc/fstab | awk /prjquota/
  register: prjquota
  changed_when: false

- name: Create bro quota project id
  getent:
    database: group
    split: ':'
    key: bro
  when: rock_mounts is defined and (prjquota.stdout|length>0)

- name: Map bro quota project id to name
  lineinfile:
    create: true
    state: present
    insertafter: EOF
    path: /etc/projid
    line: "bro:{{ getent_group.bro[1] }}"
  when: rock_mounts is defined and (prjquota.stdout|length>0)

- name: Define bro quota project directories
  lineinfile:
    create: true
    state: present
    insertafter: EOF
    path: /etc/projects
    line: "{{ getent_group.bro[1] }}:{{ bro_data_dir }}"
  when: rock_mounts is defined and (prjquota.stdout|length>0)

- name: set bro weight
  set_fact:
    bro_weight: "{{ rock_services | selectattr('name', 'equalto', 'bro') | map(attribute='quota_weight') | first }}"
  when: bro_quota is not defined and (prjquota.stdout|length>0)

- name: set bro quota if not user defined
  set_fact:
    bro_quota: "{{ rock_mounts.size_total | int / xfs_quota_weight | int * bro_weight | int }}"
  when: bro_quota is not defined and (prjquota.stdout|length>0)

- name: set bro project quota
  xfs_quota:
    type: project
    name: bro
    bhard: "{{ bro_quota }}"
    state: present
    mountpoint: "{{ rock_mounts.mount }}"
  when: rock_mounts is defined and (prjquota.stdout|length>0)

- name: Enable and start bro
  service:
    name: bro
    state: "{{ 'started' if rock_services | selectattr('name', 'equalto', 'bro') | map(attribute='enabled') | bool else 'stopped' }}"
    enabled: "{{ rock_services | selectattr('name', 'equalto', 'bro') | map(attribute='enabled') | bool }}"
  notify: Reload bro

- name: Apply Logstash role
  include_role:
    name: logstash
    apply:
      delegate_to: "{{ host }}"
      vars:
        logstash_configs:
          - { src: 'ls-input-bro.j2', dest: 'logstash-100-input-kafka-zeek.conf' }
  loop:
    "{{ groups['logstash'] }}"
  loop_control:
    loop_var: host
