---
# handlers file for stenographer

- name: Start stenographer service
  service:
    name: stenographer
    state: "{{ 'started' if 'stenographer' in enabled_services else 'stopped' }}"

- name: Start stenographer per interface
  service:
    name: "stenographer@{{ item }}"
    state: "{{ 'started' if enable_stenographer else 'stopped' }}"
  loop: "{{ stenographer_monitor_interfaces }}"

- name: Restart stenographer per interface
  service:
    name: "stenographer@{{ item }}"
    state: restarted
  loop: "{{ stenographer_monitor_interfaces }}"
