---
# deploy.yml - Common tasks for ROCK
- import_tasks: prechecks.yml
- import_tasks: configure.yml
- import_tasks: configure-time.yml
- import_tasks: configure-pipelining.yml
- import_tasks: install.yml

...
