---
# timedatectl.yml - configure ntp
- name: Install chrony
  yum:
    name: chrony
    state: installed

- name: Enable and start chrony
  service:
    name: chronyd
    enabled: yes
    state: started

- name: Set system timezone
  command: /usr/bin/timedatectl set-timezone UTC
  when: ansible_date_time.tz != "UTC"

- name: Check if RTC set to UTC
  shell: timedatectl | awk '/RTC in local/ { print $5 }'
  changed_when: false
  register: chrony_local_utc

- name: Set system hardware clock to UTC
  command: /usr/bin/timedatectl set-local-rtc no
  when: chrony_local_utc == 'yes'

- name: Check if NTP is enabled
  shell: timedatectl | awk '/NTP enabled/ { print $3 }'
  changed_when: false
  register: chrony_ntp_enabled

- name: Set NTP enabled
  command: /usr/bin/timedatectl set-ntp yes
  when: chrony_ntp_enabled == 'no'
