---

- name: Install packages
  yum:
    name:
      - java-1.8.0-openjdk-headless
      - elasticsearch
    state: installed

- name: Create elasticsearch directory
  file:
    path: "{{ es_data_dir }}"
    mode: 0755
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    state: directory

- name: Setup elasticsearch config
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: "{{ es_group }}"
    mode: 0640
  notify: Restart elasticsearch

- name: Create elasticsearch systemd override dir
  file:
    path: /etc/systemd/system/elasticsearch.service.d
    owner: root
    group: root
    mode: 0755
    state: directory
  notify:
    - Reload systemd
    - Restart elasticsearch

- name: Enable elasticsearch memlock in service override
  copy:
    content: "{{ es_memlock_override }}"
    dest: /etc/systemd/system/elasticsearch.service.d/override.conf
    mode: 0644
    owner: root
    group: root
  notify:
    - Reload systemd
    - Restart elasticsearch

- name: Setup elasticsearch JVM options
  template:
    src: templates/es-jvm.options.j2
    dest: /etc/elasticsearch/jvm.options
    mode: 0640
    owner: root
    group: "{{ es_group }}"
  notify: Restart elasticsearch

- name: Enable and start elasticsearch
  service:
    name: elasticsearch
    state: "started"
    enabled: "{{ enable_elasticsearch }}"

- name: Configure firewall ports
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes
  when: groups['elasticsearch'] | count > 1
  loop:
    - 9200
    - 9300

- name: Flush handlers
  meta: flush_handlers

- name: Wait for elasticsearch to become ready
  wait_for:
    host: "{{ ansible_host }}"
    port: 9200
  run_once: true

- name: Check for default mapping template
  uri:
    method: "GET"
    url: "{{ es_url }}/_template/default"
  failed_when: False
  register: default_index_template
  run_once: true

- name: Load default elasticsearch mapping template
  uri:
    method: PUT
    url: "{{ es_url }}/_template/default"
    body: "{{ lookup('file', 'default-mapping.json')}}"
    body_format: json
  when: with_elasticsearch and default_index_template.status != 200
  run_once: true

- name: Blanket install/update elasticsearch mappings
  command: ./import-index-templates.sh "{{ es_url }}"
  args:
    chdir: "{{ rock_module_dir }}/configuration/elasticsearch"
  changed_when: false
  run_once: true
