---
dependencies:
  - name: Install and configure filebeat
    role: filebeat
    vars:
      filebeat_configs:
        - { src: 'fb-suricata.yml.j2', dest: 'suricata.yml' }

  - name: Install and configure logstash
    role: logstash
    vars:
      logstash_configs:
        - { src: 'ls-input-suricata.j2', dest: '100-input-suricata.conf' }
        - { src: 'ls-filter-suricata.j2', dest: '500-filter-suricata.conf' }
        - { src: 'ls-output-suricata.j2', dest: '999-output-suricata.conf' }
