#!/bin/bash

set -e

OPTIND=1
pkgfile=""
dest="repo"
distro=$(cat /etc/os-release | grep -e '^ID="' | cut -d'"' -f 2)
releasever=$(cat /etc/os-release | grep -e '^VERSION_ID=' | cut -d'"' -f 2)
basearch=$(uname -p)
repofile=""
pkgcount=5

while getopts "h?d:D:r:R:c:a:" opt; do
  case "$opt" in
  h|\?)
    cat <<EOF
Usage: $(basename $0) [-d repo_directory] [-D distrobution] [-r release_version] [-a base_arch] [-c packages_per_loop] [-R repo_file] package_list
    -d  Directory path to save repository
    -D  Linux distrobution
    -r  Linux distrobution release version
    -a  Base architechture
    -c  Number of packages to download at a time
    -R  Repositories to add to /etc/yum.repos.d before execution
EOF
    exit 0
    ;;
  d)
    dest=$OPTARG
    ;;
  D)
    distro=$OPTARG
    ;;
  r)
    releasever=$OPTARG
    ;;
  a)
    basearch=$OPTARG
    ;;
  c)
    pkgcount=$OPTARG
    ;;
  R)
    repofile=$OPTARG
    ;;
  esac
done

shift $((OPTIND-1))
[ "$1" = "--" ] && shift

pkgfile=$1

if [ -z "${pkgfile// }" ]; then
  echo "Package list required";
  exit 1;
fi

pkgfile=$( cd $(dirname $pkgfile); pwd -P)/$(basename $pkgfile)

if [ ! -f "$1" ]; then
  echo "Invalid package list";
  exit 1;
fi

if [ ! -z "$repofile" ]; then
  repofile=" -v $( cd $(dirname $repofile); pwd -P)/$(basename $repofile):/etc/yum.repos.d/fetcher.repo"
fi

if [ ! "$2" = "entrypoint" -a ! -f /usr/bin/docker ]; then
  echo "Docker not found";
  exit 1;
fi

if [ "$2" = "entrypoint" -a -f /usr/bin/docker ]; then
  echo "Use a distrobution that does not contain docker";
  exit 1;
fi

dest=$( cd $(dirname $dest); pwd -P)/$(basename $dest)
mkdir -p $dest

if [ "$2" = "entrypoint" -a ! -f /usr/bin/docker  ]; then
  yum -y install createrepo
  cat $pkgfile > /tmp/.tmp-pkg-list.txt
  while [ $(cat /tmp/.tmp-pkg-list.txt | wc -l) -gt 1 ]; do
    yum -y autoremove $(head -n +$pkgcount /tmp/.tmp-pkg-list.txt | tr '\n' ' ');
    yum --downloadonly --downloaddir=/repo/$distro/$releasever/offline/$basearch/ -y install $(head -n +$pkgcount /tmp/.tmp-pkg-list.txt | tr '\n' ' ');
    echo "$(tail -n +$((pkgcount + 1)) /tmp/.tmp-pkg-list.txt)" > /tmp/.tmp-pkg-list.txt
  done;
  yum -y install createrepo
  createrepo /repo/$distro/$releasever/offline/$basearch
  chmod -R o-w+r /repo/$distro/$releasever/offline
else
  script_file=$( cd $(dirname $0); pwd -P)/$(basename $0)
  docker run --rm --privileged -ti -v $dest:/repo$repofile -v $script_file:$script_file -v $pkgfile:$pkgfile $distro $script_file -d $dest -D $distro -r $releasever -a $basearch -c $pkgcount $pkgfile entrypoint
fi
