%YAML 1.1
---
rock_version: 2.2.0
rock_online_install: true
rock_sysctl_file: /etc/sysctl.d/10-ROCK.conf
rock_data_dir: /data
rocknsm_dir: /opt/rocknsm
rock_data_user: root
rock_data_group: root
rock_monifs: "{{ ansible_interfaces | difference(['lo', ansible_default_ipv4.interface | default('lo') ])| list }}"
rock_mgmt_nets: [ "0.0.0.0/0" ]
rock_cache_dir: /srv/rocknsm/support
pulledpork_rules:
  - { url: "https://snort.org/downloads/community/", file: "community-rules.tar.gz", apikey: "Community", test: "{{not with_suricata and with_snort}}" }
  - { url: "https://www.snort.org/reg-rules/", file: "snortrules-snapshot.tar.gz", apikey: "796f26a2188c4c953ced38ff3ec899d8ae543350", test: "{{not with_suricata and with_snort}}" }
  - { url: "https://rules.emergingthreats.net/", file: "emerging.rules.tar.gz", apikey: "open-nogpl" }
  - { url: "http://talosintel.com/feeds/ip-filter.blf", file: "IPBLACKLIST", apikey: "open" }

#### Retention Configuration ####
elastic_close_interval: 15
elastic_delete_interval: 60
kafka_retention: 168
suricata_retention: 3
bro_log_retention: 0
bro_stats_retention: 0

# Feature options - Don't flip these unless you know what you're doing
# These control if the service is installed
with_stenographer: true
with_docket: true
with_bro: true
with_suricata: true
with_snort: false
with_pulledpork: true
with_logstash: true
with_elasticsearch: true
with_kibana: true
with_filebeat: true
with_zookeeper: true
with_kafka: true
with_nginx: true
with_lighttpd: true
with_fsf: true

# Feature options - Don't flip these unless you know what you're doing
# These control if the systemd service is enabled
enable_stenographer: false
enable_docket: false
enable_bro: true
enable_suricata: true
enable_snort: false
enable_pulledpork: true
enable_logstash: true
enable_elasticsearch: true
enable_kibana: true
enable_filebeat: true
enable_zookeeper: true
enable_kafka: true
enable_nginx: true
enable_lighttpd: true
enable_fsf: false

rocknsm_package_list:
  - java-1.8.0-openjdk-headless
  - jq
  - GeoIP
  - GeoIP-update
  - tcpreplay
  - tcpdump
  - bats
  - policycoreutils-python
  - htop
  - vim
  - git
  - tmux
  - nmap-ncat
  - logrotate
  - perl-LWP-Protocol-https
  - perl-Sys-Syslog
  - perl-Crypt-SSLeay
  - perl-Archive-Tar


http_tls_crt: /etc/pki/tls/certs/http_tls_crt.pem
http_tls_pub: /etc/pki/tls/certs/http_tls_pub.pem
http_tls_key: /etc/pki/tls/private/http_tls_key.pem
http_tls_combined: /etc/pki/tls/private/httpd-combined.pem
http_tls_dhparams: /etc/pki/tls/misc/http_tls_dhparams.pem

docket_web_pemfile: "{{ http_tls_combined }}"
docket_web_dhparams: "{{ http_tls_dhparams }}"

epel_baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/
epel_gpgurl:  https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
elrepo_baseurl: http://elrepo.org/linux/kernel/el7/x86_64/
elrepo_gpgurl: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
elastic_baseurl: https://artifacts.elastic.co/packages/5.x/yum
elastic_gpgurl: https://artifacts.elastic.co/GPG-KEY-elasticsearch
pulledpork_release: 0.7.2
pulledpork_url: "https://github.com/shirkdog/pulledpork/archive/{{ pulledpork_release }}.tar.gz"
pulledpork_filename: "pulledpork-{{ pulledpork_release }}.tar.gz"
pulledpork_engine_basepath: "/etc/{{ \"suricata\" if with_suricata else \"snort\" }}"

rocknsm_baseurl: https://packagecloud.io/rocknsm/2/el/7/$basearch
rocknsm_gpgurl: https://packagecloud.io/rocknsm/2/gpgkey
rocknsm_local_baseurl: file:///srv/rocknsm
bro_user: bro
bro_group: bro
bro_data_dir: "{{ rock_data_dir }}/bro"
bro_prefix: /usr
bro_sysconfig_dir: /etc/bro
bro_site_dir: /usr/share/bro/site
bro_cpu: "{{ (ansible_processor_vcpus // 2) if (ansible_processor_vcpus <= 16) else 8 }}"
bro_rockscripts_repo: https://github.com/rocknsm/rock-scripts.git
bro_rockscripts_branch: master
bro_rockscripts_filename: "rock-scripts_{{ bro_rockscripts_branch | replace('/', '-') }}.tar.gz"
rock_dashboards_repo: https://github.com/rocknsm/rock-dashboards.git
rock_dashboards_branch: master
rock_dashboards_url: "https://github.com/rocknsm/rock-dashboards/archive/{{ rock_dashboards_branch }}.tar.gz"
rock_dashboards_filename: "rock-dashboards_{{ rock_dashboards_branch | replace('/', '-') }}.tar.gz"
rock_dashboards_version: 2.0
stenographer_user: stenographer
stenographer_group: stenographer
stenographer_data_dir: "{{ rock_data_dir }}/stenographer"
suricata_user: suricata
suricata_group: suricata
suricata_data_dir: "{{ rock_data_dir }}/suricata"
pulled_pork_repo: https://github.com/shirkdog/pulledpork.git
pulled_pork_oinkcode: 796f26a2188c4c953ced38ff3ec899d8ae543350
fsf_user: fsf
fsf_group: fsf
fsf_data_dir: "{{ rock_data_dir }}/fsf"
fsf_archive_dir: "{{ fsf_data_dir }}/archive"
fsf_client_logfile: "{{ fsf_data_dir }}/client.log"
kafka_user: kafka
kafka_group: kafka
kafka_data_dir: "{{ rock_data_dir }}/kafka"
kafka_config_path: /etc/kafka/server.properties
es_user: elasticsearch
es_group: elasticsearch
es_data_dir: "{{ rock_data_dir }}/elasticsearch"
es_log_dir: /var/log/elasticsearch
es_cluster_name: rocknsm
es_node_name: "{{ ansible_hostname }}"
es_mem: "{{ (ansible_memtotal_mb // 1024 // 2) if (ansible_memtotal_mb // 1024) < 64 else 31 }}"
es_url: "http://localhost:9200"
es_memlock_override: |
  [Service]
  LimitMEMLOCK=infinity
logstash_user: logstash
logstash_group: logstash
...
