#!/usr/bin/expect -f
set timeout 180

#Automate the db.pl init action for Moloch
spawn /data/moloch/db/db.pl {{ moloch_elastic_url }} init

expect -ex "Type \"INIT\" to continue - do you want to erase everything??"
send "INIT\r"

expect eof
