---
- name: docker | check existing secret_key
  shell: >
    cat /etc/docket/prod.yaml | awk '/^SECRET_KEY/ {print $2}'
  register: docket_prod
  changed_when: false

- debug: msg="{{ docket_prod }}"

- name: docket | keep existing secret_key
  set_fact: docket_secret="{{ docket_prod.stdout }}"
  when: '"CHANGE_THIS" not in docket_prod.stdout'

- name: docket | set production docket config
  template:
    src:  docket_prod.yaml.j2
    dest: /etc/docket/prod.yaml
  notify:
    - docket | restart docket uwsgi
    - docket | restart docket celery services

- name: docket | enable redis
  service:
    name: redis
    enabled: yes
  notify: docket | restart redis

- name: docket | enable docket celery services
  service:
    name: "{{ item }}"
    enabled: yes
  notify: docket | restart docket celery services
  with_items:
    - docket-celery-io
    - docket-celery-query

- name: docket | enable docket uwsgi service
  service:
    name: docket
    enabled: yes
  notify: docket | restart docket uwsgi
